### ISSUE TITLE
请问如何调试代码？

### ISSUE THREAD

**Issue by jindongjie** [HeBianGu/Avalonia-Controls#1]
我克隆项目到本地后找不到可执行启动项，大佬求助！

**Comment by jindongjie** [comment]
15:39:43.870 [Information] 0 Stopping previewer process
15:39:43.994 [Error]  No executable found

**Comment by jindongjie** [comment]
![Screenshot 2024-05-30 154103](https://github.com/HeBianGu/Avalonia-Controls/assets/141336798/c8e14b26-a9a0-4b45-b56f-84aa77329b05)

**Comment by jindongjie** [comment]
试了几个启动项都不行

**Comment by HeBianGu** [comment]
用这个路径的solution，"Avalonia-Controls\Solution\Avalonia-Controls.sln"，执行HeBianGu.Test.Main.Desktop.csprj，外部的Package.sln用来nuget用的.

**Comment by HeBianGu** [comment]
https://github.com/HeBianGu/Avalonia-Controls/wiki

**Comment by jindongjie** [comment]
> https://github.com/HeBianGu/Avalonia-Controls/wiki

好的，我现在试一下

**Comment by jindongjie** [comment]
可以了：）
